/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forest;

/**
 *
 * @author abc
 */
public class EditTreeParameters extends javax.swing.JFrame {

    /**
     * Creates new form EditTreeParameters
     */
    public EditTreeParameters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMutP = new javax.swing.JLabel();
        LabelMutPerc = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        LabelMaxage = new javax.swing.JLabel();
        labelMaxAge = new javax.swing.JLabel();
        slider2 = new javax.swing.JSlider();
        labelNumTrees = new javax.swing.JLabel();
        LabelInitialTrees = new javax.swing.JLabel();
        slider3 = new javax.swing.JSlider();
        LabelSeedEnergy = new javax.swing.JLabel();
        LabelEnergyToSeed = new javax.swing.JLabel();
        slider4 = new javax.swing.JSlider();
        labelTreeHeight = new javax.swing.JLabel();
        LabelMaxHeight = new javax.swing.JLabel();
        slider5 = new javax.swing.JSlider();
        LabelLArea = new javax.swing.JLabel();
        LabelLeafArea = new javax.swing.JLabel();
        slider6 = new javax.swing.JSlider();
        slider7 = new javax.swing.JSlider();
        labelIEnergy = new javax.swing.JLabel();
        LabelInitialEnergy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Forest Simulation: Edit Tree Parameters");
        setMinimumSize(new java.awt.Dimension(570, 430));
        getContentPane().setLayout(null);

        LabelMutP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMutP.setText("Mutation percent");
        getContentPane().add(LabelMutP);
        LabelMutP.setBounds(340, 35, 130, 17);

        LabelMutPerc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMutPerc.setText("2");
        LabelMutPerc.setPreferredSize(new java.awt.Dimension(30, 14));
        getContentPane().add(LabelMutPerc);
        LabelMutPerc.setBounds(480, 30, 60, 20);

        slider1.setMajorTickSpacing(2);
        slider1.setMaximum(10);
        slider1.setToolTipText("");
        slider1.setValue(2);
        slider1.setPreferredSize(new java.awt.Dimension(200, 30));
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });
        getContentPane().add(slider1);
        slider1.setBounds(50, 30, 230, 30);

        LabelMaxage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxage.setText("100");
        getContentPane().add(LabelMaxage);
        LabelMaxage.setBounds(480, 130, 60, 20);

        labelMaxAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMaxAge.setText("Max Age");
        getContentPane().add(labelMaxAge);
        labelMaxAge.setBounds(340, 130, 80, 20);

        slider2.setMaximum(10000);
        slider2.setMinimum(10);
        slider2.setMinorTickSpacing(50);
        slider2.setValue(100);
        slider2.setPreferredSize(new java.awt.Dimension(200, 30));
        slider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider2StateChanged(evt);
            }
        });
        getContentPane().add(slider2);
        slider2.setBounds(50, 130, 230, 30);

        labelNumTrees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNumTrees.setText("Initial no. of trees");
        getContentPane().add(labelNumTrees);
        labelNumTrees.setBounds(340, 185, 130, 17);

        LabelInitialTrees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelInitialTrees.setText("100");
        getContentPane().add(LabelInitialTrees);
        LabelInitialTrees.setBounds(480, 180, 60, 20);

        slider3.setMaximum(500);
        slider3.setMinimum(1);
        slider3.setMinorTickSpacing(20);
        slider3.setValue(100);
        slider3.setPreferredSize(new java.awt.Dimension(130, 23));
        slider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider3StateChanged(evt);
            }
        });
        getContentPane().add(slider3);
        slider3.setBounds(50, 180, 230, 30);

        LabelSeedEnergy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelSeedEnergy.setText("Energy to seed");
        getContentPane().add(LabelSeedEnergy);
        LabelSeedEnergy.setBounds(340, 235, 120, 17);

        LabelEnergyToSeed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelEnergyToSeed.setText("450");
        getContentPane().add(LabelEnergyToSeed);
        LabelEnergyToSeed.setBounds(480, 230, 60, 20);

        slider4.setForeground(new java.awt.Color(255, 0, 51));
        slider4.setMaximum(10000);
        slider4.setMinimum(50);
        slider4.setMinorTickSpacing(50);
        slider4.setToolTipText("");
        slider4.setValue(450);
        slider4.setPreferredSize(new java.awt.Dimension(130, 23));
        slider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider4StateChanged(evt);
            }
        });
        getContentPane().add(slider4);
        slider4.setBounds(50, 230, 230, 30);

        labelTreeHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTreeHeight.setText("Max Tree Height");
        getContentPane().add(labelTreeHeight);
        labelTreeHeight.setBounds(340, 285, 120, 17);

        LabelMaxHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxHeight.setText("150");
        getContentPane().add(LabelMaxHeight);
        LabelMaxHeight.setBounds(480, 280, 60, 20);

        slider5.setMaximum(300);
        slider5.setMinimum(10);
        slider5.setMinorTickSpacing(20);
        slider5.setValue(150);
        slider5.setPreferredSize(new java.awt.Dimension(130, 23));
        slider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider5StateChanged(evt);
            }
        });
        getContentPane().add(slider5);
        slider5.setBounds(50, 280, 230, 30);

        LabelLArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelLArea.setText("Leaf Area");
        getContentPane().add(LabelLArea);
        LabelLArea.setBounds(340, 335, 70, 17);

        LabelLeafArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelLeafArea.setText("10");
        getContentPane().add(LabelLeafArea);
        LabelLeafArea.setBounds(480, 330, 60, 20);

        slider6.setMinimum(1);
        slider6.setMinorTickSpacing(10);
        slider6.setValue(10);
        slider6.setPreferredSize(new java.awt.Dimension(130, 23));
        slider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider6StateChanged(evt);
            }
        });
        getContentPane().add(slider6);
        slider6.setBounds(50, 330, 230, 30);

        slider7.setMaximum(300);
        slider7.setValue(190);
        slider7.setPreferredSize(new java.awt.Dimension(200, 30));
        slider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider7StateChanged(evt);
            }
        });
        getContentPane().add(slider7);
        slider7.setBounds(50, 80, 230, 30);

        labelIEnergy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelIEnergy.setText("Initial Energy");
        getContentPane().add(labelIEnergy);
        labelIEnergy.setBounds(340, 85, 110, 17);

        LabelInitialEnergy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelInitialEnergy.setText("190");
        getContentPane().add(LabelInitialEnergy);
        LabelInitialEnergy.setBounds(480, 80, 60, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest/resources/tree background.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        LabelMutPerc.setText(slider1.getValue() + "");
        Constants.TreeMutStemLength = slider1.getValue() * Constants.TreeMaxStemLength / 100;
        Constants.TreeMutLeafArea = slider1.getValue() * Constants.TreeMaxLeafArea / 100;// TODO add your handling code here:
    }//GEN-LAST:event_slider1StateChanged

    private void slider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider2StateChanged
        LabelMaxage.setText(slider2.getValue() + "");
        Constants.Treemaxagecopy = slider2.getValue();

    }//GEN-LAST:event_slider2StateChanged

    private void slider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider3StateChanged
        LabelInitialTrees.setText(slider3.getValue() + "");
        Constants.ArenaInitialTrees = slider3.getValue();

    }//GEN-LAST:event_slider3StateChanged

    private void slider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider4StateChanged
        LabelEnergyToSeed.setText(slider4.getValue() + "");
        Constants.TreeEnergyToSeed = slider4.getValue();// TODO add your handling code here:
    }//GEN-LAST:event_slider4StateChanged

    private void slider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider5StateChanged
        LabelMaxHeight.setText(slider5.getValue() + "");
        Constants.TreeMaxStemLength = slider5.getValue();// TODO add your handling code here:
    }//GEN-LAST:event_slider5StateChanged

    private void slider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider6StateChanged
        LabelLeafArea.setText(slider6.getValue() + "");
        Constants.TreeMaxLeafArea = slider6.getValue();// TODO add your handling code here:
    }//GEN-LAST:event_slider6StateChanged

    private void slider7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider7StateChanged
        LabelInitialEnergy.setText(slider7.getValue() + "");
        Constants.TreeInitialEnergy = slider7.getValue();

    }//GEN-LAST:event_slider7StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTreeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTreeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTreeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTreeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditTreeParameters().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEnergyToSeed;
    private javax.swing.JLabel LabelInitialEnergy;
    private javax.swing.JLabel LabelInitialTrees;
    private javax.swing.JLabel LabelLArea;
    private javax.swing.JLabel LabelLeafArea;
    private javax.swing.JLabel LabelMaxHeight;
    private javax.swing.JLabel LabelMaxage;
    private javax.swing.JLabel LabelMutP;
    private javax.swing.JLabel LabelMutPerc;
    private javax.swing.JLabel LabelSeedEnergy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIEnergy;
    private javax.swing.JLabel labelMaxAge;
    private javax.swing.JLabel labelNumTrees;
    private javax.swing.JLabel labelTreeHeight;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    private javax.swing.JSlider slider3;
    private javax.swing.JSlider slider4;
    private javax.swing.JSlider slider5;
    private javax.swing.JSlider slider6;
    private javax.swing.JSlider slider7;
    // End of variables declaration//GEN-END:variables
}
