/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forest;

import java.awt.Color;
import java.lang.reflect.Field;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class EditEnvironmentParameters extends javax.swing.JFrame {

    /**
     * Creates new form EditTreeParameters
     */
    public EditEnvironmentParameters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMutP = new javax.swing.JLabel();
        LabelWindBias = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        slider2 = new javax.swing.JSlider();
        LabelMutP1 = new javax.swing.JLabel();
        LabelWindBias1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setTitle(" Edit Environmental Parameters");
        setMinimumSize(new java.awt.Dimension(590, 410));
        getContentPane().setLayout(null);

        LabelMutP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMutP.setText("Energy from Light");
        getContentPane().add(LabelMutP);
        LabelMutP.setBounds(280, 60, 130, 17);

        LabelWindBias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelWindBias.setText("120");
        LabelWindBias.setPreferredSize(new java.awt.Dimension(30, 14));
        getContentPane().add(LabelWindBias);
        LabelWindBias.setBounds(440, 60, 60, 20);

        slider1.setMajorTickSpacing(10);
        slider1.setToolTipText("");
        slider1.setPreferredSize(new java.awt.Dimension(200, 30));
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });
        getContentPane().add(slider1);
        slider1.setBounds(20, 20, 230, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Introduce Calamities");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 100, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Left Side");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 150, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Right Side");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 150, 70, 17);

        jButton1.setText("Kill All Plants");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 190, 120, 25);

        jButton2.setText("Kill All Plants");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 190, 120, 25);

        jButton3.setText("Kill All Camoflauged Giraffes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 230, 210, 25);

        jButton4.setText("Kill All Camoflauged Giraffes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 230, 210, 25);

        jButton5.setText("Kill All Lions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 270, 120, 25);

        jButton6.setText("Kill All Lions");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(60, 270, 120, 25);

        jButton7.setText("Kill Trees Of A Particular Colour");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(320, 310, 220, 25);

        jButton8.setText("Kill Trees Of A Particular Colour");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 310, 220, 25);

        slider2.setMajorTickSpacing(10);
        slider2.setMaximum(200);
        slider2.setToolTipText("");
        slider2.setValue(120);
        slider2.setPreferredSize(new java.awt.Dimension(200, 30));
        slider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider2StateChanged(evt);
            }
        });
        getContentPane().add(slider2);
        slider2.setBounds(20, 60, 230, 30);

        LabelMutP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMutP1.setText("WindBias");
        getContentPane().add(LabelMutP1);
        LabelMutP1.setBounds(280, 20, 130, 17);

        LabelWindBias1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelWindBias1.setText("50");
        LabelWindBias1.setPreferredSize(new java.awt.Dimension(30, 14));
        getContentPane().add(LabelWindBias1);
        LabelWindBias1.setBounds(440, 20, 60, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 100, 560, 2);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 140, 560, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(270, 140, 0, 2);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(288, 140, 2, 230);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest/resources/blue.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 610, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        LabelWindBias1.setText(slider1.getValue() + "");
        Constants.ArenaWindBias=slider1.getValue()/100.0;
    }//GEN-LAST:event_slider1StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for(Tree t:Forest.arrayOfAliveTrees){
            if(t!=null&&t.x<Constants.ArenaMaxX/2)
                t.kill();
        }
        
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(Tree t:Forest.arrayOfAliveTrees){
            if(t!=null&&t.x>Constants.ArenaMaxX/2)
                t.kill();
        }
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for(giraffe g:Forest.arrayOfAliveGiraffes){
            if(g!=null&&g.dna.camouflage.fromFemaleParent==true&&g.dna.camouflage.fromMaleParent&&g.x<=Constants.ArenaMaxX/2)
                g.kill();
        }
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        for(giraffe g:Forest.arrayOfAliveGiraffes){
            if(g!=null&&g.dna.camouflage.fromFemaleParent==true&&g.dna.camouflage.fromMaleParent&&g.x>=Constants.ArenaMaxX/2)
                g.kill();
        }
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        for(Lion l:Forest.arrayOfAliveLions){
            if(l!=null&&l.x<=Constants.ArenaMaxX/2)
                l.kill();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         for(Lion l:Forest.arrayOfAliveLions){
            if(l!=null&&l.x>=Constants.ArenaMaxX/2)
                l.kill();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try{
       Color todelete;
        String s=JOptionPane.showInputDialog(gui.g6, "Enter name of colour without spaces in lowercase", "Enter Color", JOptionPane.INFORMATION_MESSAGE);
        try{
        
        Field field = Class.forName("java.awt.Color").getField(s);
    todelete = (Color)field.get(null);
        }
        catch (Exception e) {
    todelete = null; // Not defined
}
        if(todelete!=null){
            for(Tree t:Forest.arrayOfAliveTrees){
                if(t!=null&&Forest.RGBDistance(todelete, t.color)<=Constants.TreeColDistToRepr&&t.x<=Constants.ArenaMaxX/2)
                    t.kill();
            }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(gui.g6, "An Error Occured", "Error", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
       Color todelete;
        String s=JOptionPane.showInputDialog(gui.g6, "Enter name of colour without spaces in lowercase", "Enter Color", JOptionPane.INFORMATION_MESSAGE);
        try{
        
        Field field = Class.forName("java.awt.Color").getField(s);
    todelete = (Color)field.get(null);
        }
        catch (Exception e) {
    todelete = null; // Not defined
}
        if(todelete!=null){
            for(Tree t:Forest.arrayOfAliveTrees){
                if(t!=null&&Forest.RGBDistance(todelete, t.color)<=Constants.TreeColDistToRepr&&t.x>=Constants.ArenaMaxX/2)
                    t.kill();
            }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(gui.g6, "An Error Occured", "Error", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void slider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider2StateChanged
        LabelWindBias1.setText(slider1.getValue() + "");
        Constants.ArenaEnergyOfLightBeam=(int)(slider1.getValue()/100);
    }//GEN-LAST:event_slider2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEnvironmentParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEnvironmentParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEnvironmentParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEnvironmentParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditEnvironmentParameters().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMutP;
    private javax.swing.JLabel LabelMutP1;
    private javax.swing.JLabel LabelWindBias;
    private javax.swing.JLabel LabelWindBias1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSlider slider1;
    private javax.swing.JSlider slider2;
    // End of variables declaration//GEN-END:variables
}
