/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forest;

/**
 *
 * @author abc
 */
public class EditGiraffeParameters extends javax.swing.JFrame {

    /**
     * Creates new form EditGiraffeParameters
     */
    public EditGiraffeParameters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FertilisationFactorSlider = new javax.swing.JSlider();
        MutationPercentSlider = new javax.swing.JSlider();
        InitialEnergySlider = new javax.swing.JSlider();
        InitialGiraffesSlider = new javax.swing.JSlider();
        EnergyToMateSlider = new javax.swing.JSlider();
        MaxGiraffeHeightSlider = new javax.swing.JSlider();
        NeckBodyRatioSlider = new javax.swing.JSlider();
        MaxAgeSlider = new javax.swing.JSlider();
        FertilisationFactor = new javax.swing.JLabel();
        MutationPercent = new javax.swing.JLabel();
        InitialEnergy = new javax.swing.JLabel();
        InitialGiraffes = new javax.swing.JLabel();
        MaxAge = new javax.swing.JLabel();
        NeckBodyRatio = new javax.swing.JLabel();
        MaxgiraffeHeight = new javax.swing.JLabel();
        EnergyToMate = new javax.swing.JLabel();
        LabelFertilisationFactor = new javax.swing.JLabel();
        LabelMutPerc = new javax.swing.JLabel();
        LabelInitialEnergy = new javax.swing.JLabel();
        LabelInitialGiraffes = new javax.swing.JLabel();
        LabelEnergyToMate = new javax.swing.JLabel();
        LabelMaxGiraffeHeight = new javax.swing.JLabel();
        LabelNeckBodyRatio = new javax.swing.JLabel();
        LabelMaxAge = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Forest Simulation: Edit Giraffe Parameters");
        setMinimumSize(new java.awt.Dimension(600, 465));
        getContentPane().setLayout(null);

        FertilisationFactorSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        FertilisationFactorSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FertilisationFactorSliderStateChanged(evt);
            }
        });
        getContentPane().add(FertilisationFactorSlider);
        FertilisationFactorSlider.setBounds(30, 375, 200, 30);

        MutationPercentSlider.setMaximum(10);
        MutationPercentSlider.setToolTipText("");
        MutationPercentSlider.setValue(2);
        MutationPercentSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        MutationPercentSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MutationPercentSliderStateChanged(evt);
            }
        });
        getContentPane().add(MutationPercentSlider);
        MutationPercentSlider.setBounds(30, 25, 200, 30);

        InitialEnergySlider.setMaximum(1000);
        InitialEnergySlider.setValue(100);
        InitialEnergySlider.setPreferredSize(new java.awt.Dimension(200, 30));
        InitialEnergySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InitialEnergySliderStateChanged(evt);
            }
        });
        getContentPane().add(InitialEnergySlider);
        InitialEnergySlider.setBounds(30, 75, 200, 30);

        InitialGiraffesSlider.setMaximum(25);
        InitialGiraffesSlider.setToolTipText("");
        InitialGiraffesSlider.setValue(30);
        InitialGiraffesSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        InitialGiraffesSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InitialGiraffesSliderStateChanged(evt);
            }
        });
        getContentPane().add(InitialGiraffesSlider);
        InitialGiraffesSlider.setBounds(30, 125, 200, 30);

        EnergyToMateSlider.setMaximum(2000);
        EnergyToMateSlider.setToolTipText("");
        EnergyToMateSlider.setValue(350);
        EnergyToMateSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        EnergyToMateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EnergyToMateSliderStateChanged(evt);
            }
        });
        getContentPane().add(EnergyToMateSlider);
        EnergyToMateSlider.setBounds(30, 175, 200, 30);

        MaxGiraffeHeightSlider.setMaximum(250);
        MaxGiraffeHeightSlider.setValue(140);
        MaxGiraffeHeightSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        MaxGiraffeHeightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MaxGiraffeHeightSliderStateChanged(evt);
            }
        });
        getContentPane().add(MaxGiraffeHeightSlider);
        MaxGiraffeHeightSlider.setBounds(30, 225, 200, 30);

        NeckBodyRatioSlider.setMaximum(2);
        NeckBodyRatioSlider.setValue(1);
        NeckBodyRatioSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        NeckBodyRatioSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NeckBodyRatioSliderStateChanged(evt);
            }
        });
        getContentPane().add(NeckBodyRatioSlider);
        NeckBodyRatioSlider.setBounds(30, 275, 200, 30);

        MaxAgeSlider.setMaximum(500);
        MaxAgeSlider.setValue(120);
        MaxAgeSlider.setPreferredSize(new java.awt.Dimension(200, 30));
        MaxAgeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MaxAgeSliderStateChanged(evt);
            }
        });
        getContentPane().add(MaxAgeSlider);
        MaxAgeSlider.setBounds(30, 325, 200, 30);

        FertilisationFactor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FertilisationFactor.setText("Fertilisation Factor");
        getContentPane().add(FertilisationFactor);
        FertilisationFactor.setBounds(290, 380, 200, 20);

        MutationPercent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MutationPercent.setText("Mutation Percent");
        getContentPane().add(MutationPercent);
        MutationPercent.setBounds(290, 30, 160, 20);

        InitialEnergy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InitialEnergy.setText("Initial Energy");
        getContentPane().add(InitialEnergy);
        InitialEnergy.setBounds(290, 80, 160, 20);

        InitialGiraffes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InitialGiraffes.setText("Initial no. of giraffes");
        getContentPane().add(InitialGiraffes);
        InitialGiraffes.setBounds(290, 130, 200, 20);

        MaxAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MaxAge.setText("Max Age");
        getContentPane().add(MaxAge);
        MaxAge.setBounds(290, 330, 200, 20);

        NeckBodyRatio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NeckBodyRatio.setText("Neck to body ratio");
        getContentPane().add(NeckBodyRatio);
        NeckBodyRatio.setBounds(290, 280, 200, 20);

        MaxgiraffeHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MaxgiraffeHeight.setText("Max Giraffe Height");
        getContentPane().add(MaxgiraffeHeight);
        MaxgiraffeHeight.setBounds(290, 230, 200, 20);

        EnergyToMate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnergyToMate.setText("Energy to mate");
        getContentPane().add(EnergyToMate);
        EnergyToMate.setBounds(290, 180, 200, 20);

        LabelFertilisationFactor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelFertilisationFactor.setText("50");
        LabelFertilisationFactor.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelFertilisationFactor.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelFertilisationFactor);
        LabelFertilisationFactor.setBounds(490, 380, 80, 20);

        LabelMutPerc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMutPerc.setText("2");
        LabelMutPerc.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelMutPerc.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelMutPerc);
        LabelMutPerc.setBounds(490, 30, 80, 20);

        LabelInitialEnergy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelInitialEnergy.setText("100");
        LabelInitialEnergy.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelInitialEnergy.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelInitialEnergy);
        LabelInitialEnergy.setBounds(490, 80, 80, 20);

        LabelInitialGiraffes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelInitialGiraffes.setText("30");
        LabelInitialGiraffes.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelInitialGiraffes.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelInitialGiraffes);
        LabelInitialGiraffes.setBounds(490, 130, 80, 20);

        LabelEnergyToMate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelEnergyToMate.setText("350");
        LabelEnergyToMate.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelEnergyToMate.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelEnergyToMate);
        LabelEnergyToMate.setBounds(490, 180, 80, 20);

        LabelMaxGiraffeHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxGiraffeHeight.setText("140");
        LabelMaxGiraffeHeight.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelMaxGiraffeHeight.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelMaxGiraffeHeight);
        LabelMaxGiraffeHeight.setBounds(490, 230, 80, 20);

        LabelNeckBodyRatio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNeckBodyRatio.setText("1");
        LabelNeckBodyRatio.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelNeckBodyRatio.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelNeckBodyRatio);
        LabelNeckBodyRatio.setBounds(490, 280, 80, 20);

        LabelMaxAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxAge.setText("120");
        LabelMaxAge.setMinimumSize(new java.awt.Dimension(34, 20));
        LabelMaxAge.setPreferredSize(new java.awt.Dimension(34, 20));
        getContentPane().add(LabelMaxAge);
        LabelMaxAge.setBounds(490, 330, 80, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest/resources/g.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MutationPercentSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MutationPercentSliderStateChanged
        LabelMutPerc.setText(MutationPercentSlider.getValue() + "");
        Constants.mutabsgheight = MutationPercentSlider.getValue() * Constants.gheight / 100;
        Constants.mutabsgnbratio = MutationPercentSlider.getValue() * Constants.gratio / 100;
        Constants.mutabsgangle = MutationPercentSlider.getValue() * Constants.gangle / 100;
        Constants.mutabsgspeed = MutationPercentSlider.getValue() * Constants.gmaxspeed / 100;
    }//GEN-LAST:event_MutationPercentSliderStateChanged

    private void InitialEnergySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InitialEnergySliderStateChanged
        LabelInitialEnergy.setText(InitialEnergySlider.getValue() + "");
        Constants.ginitialenergy = InitialEnergySlider.getValue();
    }//GEN-LAST:event_InitialEnergySliderStateChanged

    private void InitialGiraffesSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InitialGiraffesSliderStateChanged
        LabelInitialGiraffes.setText(InitialGiraffesSlider.getValue() + "");
        Constants.ArenaInitialGiraffes = InitialGiraffesSlider.getValue();
    }//GEN-LAST:event_InitialGiraffesSliderStateChanged

    private void EnergyToMateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EnergyToMateSliderStateChanged
        LabelEnergyToMate.setText(EnergyToMateSlider.getValue() + "");
        Constants.genergytoreproduce = EnergyToMateSlider.getValue();
    }//GEN-LAST:event_EnergyToMateSliderStateChanged

    private void MaxGiraffeHeightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MaxGiraffeHeightSliderStateChanged
        LabelMaxGiraffeHeight.setText(MaxGiraffeHeightSlider.getValue() + "");
        Constants.gheight = MaxGiraffeHeightSlider.getValue();
    }//GEN-LAST:event_MaxGiraffeHeightSliderStateChanged

    private void NeckBodyRatioSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NeckBodyRatioSliderStateChanged
        LabelNeckBodyRatio.setText(NeckBodyRatioSlider.getValue() + "");
        Constants.gratio = NeckBodyRatioSlider.getValue();
    }//GEN-LAST:event_NeckBodyRatioSliderStateChanged

    private void MaxAgeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MaxAgeSliderStateChanged
        LabelMaxAge.setText(MaxAgeSlider.getValue() + "");
        Constants.gmaxage = MaxAgeSlider.getValue();
    }//GEN-LAST:event_MaxAgeSliderStateChanged

    private void FertilisationFactorSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FertilisationFactorSliderStateChanged
        LabelFertilisationFactor.setText(FertilisationFactorSlider.getValue() + "");
        Constants.gfertilizationfactor = FertilisationFactorSlider.getValue() / 100.0;// TODO add your handling code here:
    }//GEN-LAST:event_FertilisationFactorSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGiraffeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGiraffeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGiraffeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGiraffeParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditGiraffeParameters().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnergyToMate;
    private javax.swing.JSlider EnergyToMateSlider;
    private javax.swing.JLabel FertilisationFactor;
    private javax.swing.JSlider FertilisationFactorSlider;
    private javax.swing.JLabel InitialEnergy;
    private javax.swing.JSlider InitialEnergySlider;
    private javax.swing.JLabel InitialGiraffes;
    private javax.swing.JSlider InitialGiraffesSlider;
    private javax.swing.JLabel LabelEnergyToMate;
    private javax.swing.JLabel LabelFertilisationFactor;
    private javax.swing.JLabel LabelInitialEnergy;
    private javax.swing.JLabel LabelInitialGiraffes;
    private javax.swing.JLabel LabelMaxAge;
    private javax.swing.JLabel LabelMaxGiraffeHeight;
    private javax.swing.JLabel LabelMutPerc;
    private javax.swing.JLabel LabelNeckBodyRatio;
    private javax.swing.JLabel MaxAge;
    private javax.swing.JSlider MaxAgeSlider;
    private javax.swing.JSlider MaxGiraffeHeightSlider;
    private javax.swing.JLabel MaxgiraffeHeight;
    private javax.swing.JLabel MutationPercent;
    private javax.swing.JSlider MutationPercentSlider;
    private javax.swing.JLabel NeckBodyRatio;
    private javax.swing.JSlider NeckBodyRatioSlider;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
