/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forest;

import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class GiraffeGenesDisplay extends javax.swing.JFrame {

    /**
     * Creates new form GiraffeGenesDisplay
     */
    public GiraffeGenesDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelGMaxSpeed = new javax.swing.JTextField();
        LabelGEnergyToReproduce = new javax.swing.JTextField();
        LabelGRatio = new javax.swing.JTextField();
        LabelGMaxAge = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LabelGMaxHeight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboGSex = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        TextFieldCam = new javax.swing.JComboBox();
        LabelGID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Giraffe Genes");
        setBackground(new java.awt.Color(51, 255, 255));
        setMinimumSize(new java.awt.Dimension(350, 340));
        setPreferredSize(new java.awt.Dimension(350, 340));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Maximum Age:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 50, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Maximum Speed:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Energy To Reproduce:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Neck-Body Ratio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 150, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 40, 30);

        LabelGMaxSpeed.setText("jTextField1");
        getContentPane().add(LabelGMaxSpeed);
        LabelGMaxSpeed.setBounds(230, 140, 70, 30);

        LabelGEnergyToReproduce.setText("jTextField2");
        getContentPane().add(LabelGEnergyToReproduce);
        LabelGEnergyToReproduce.setBounds(230, 110, 70, 30);

        LabelGRatio.setText("jTextField3");
        getContentPane().add(LabelGRatio);
        LabelGRatio.setBounds(230, 80, 70, 30);

        LabelGMaxAge.setText("jTextField4");
        getContentPane().add(LabelGMaxAge);
        LabelGMaxAge.setBounds(230, 50, 70, 30);

        ButtonSave.setBackground(new java.awt.Color(204, 204, 255));
        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSave);
        ButtonSave.setBounds(150, 260, 61, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Maximum Height:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 170, 140, 30);

        LabelGMaxHeight.setText("jTextField1");
        getContentPane().add(LabelGMaxHeight);
        LabelGMaxHeight.setBounds(230, 170, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sex:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 200, 80, 30);

        ComboGSex.setBackground(new java.awt.Color(204, 204, 255));
        ComboGSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));
        getContentPane().add(ComboGSex);
        ComboGSex.setBounds(230, 200, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Camoflauge Genes:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 230, 150, 30);

        TextFieldCam.setBackground(new java.awt.Color(102, 102, 255));
        TextFieldCam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CC", "Cc", "cc" }));
        getContentPane().add(TextFieldCam);
        TextFieldCam.setBounds(230, 230, 70, 30);

        LabelGID.setEditable(false);
        LabelGID.setText("jTextField1");
        getContentPane().add(LabelGID);
        LabelGID.setBounds(230, 20, 70, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest/resources/blue.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 350, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
try{
        
        for (Giraffe t : Forest.arrayOfAliveGiraffes) {
            if (t != null && t.isSelected) {
                t.dna.maxage = Integer.parseInt(LabelGMaxAge.getText());
                t.dna.neckbodyratio = Double.parseDouble(LabelGRatio.getText());
                t.dna.height = Double.parseDouble(LabelGMaxHeight.getText());
                t.dna.maxspeed = Double.parseDouble(LabelGMaxSpeed.getText());
                t.dna.energytoreproduce = Double.parseDouble(LabelGEnergyToReproduce.getText());
                if (ComboGSex.getSelectedIndex() == 0) {
                    t.gender = false;
                } else {
                    t.gender = true;
                }

                if(TextFieldCam.getSelectedIndex()==0){
                    t.dna.camouflage.fromFemaleParent=true;
                    t.dna.camouflage.fromMaleParent=true;
                }
                if(TextFieldCam.getSelectedIndex()==1){
                    t.dna.camouflage.fromFemaleParent=true;
                    t.dna.camouflage.fromMaleParent=false;
                }
                if(TextFieldCam.getSelectedIndex()==2){
                    t.dna.camouflage.fromFemaleParent=false;
                    t.dna.camouflage.fromMaleParent=false;
                }
                
            }
        }

        GUI.g4.setVisible(false);
}

catch(Exception e){
     JOptionPane.showMessageDialog(GUI.g4, "An Error Occured.Please Try Again.", "Warning", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_ButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiraffeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiraffeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiraffeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiraffeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GiraffeGenesDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSave;
    public static javax.swing.JComboBox ComboGSex;
    public static javax.swing.JTextField LabelGEnergyToReproduce;
    public static javax.swing.JTextField LabelGID;
    public static javax.swing.JTextField LabelGMaxAge;
    public static javax.swing.JTextField LabelGMaxHeight;
    public static javax.swing.JTextField LabelGMaxSpeed;
    public static javax.swing.JTextField LabelGRatio;
    public static javax.swing.JComboBox TextFieldCam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
