package forest;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.SwingWorker;
import org.jfree.ui.RefineryUtilities;

public class gui extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Arena = new tempgui();
        jPanel1 = new javax.swing.JPanel();
        CheckBoxShowLight = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        ButtonGetTreeGenes = new javax.swing.JButton();
        ButtonGetGiraffeGenes = new javax.swing.JButton();
        ButtonKillPlant = new javax.swing.JButton();
        ButtonKillGiraffe = new javax.swing.JButton();
        ButtonEditTreeParameters = new javax.swing.JButton();
        ButtonEditGiraffeParameters = new javax.swing.JButton();
        ButtonEditEnvironmentalParameters = new javax.swing.JButton();
        ButtonGetLionGenes = new javax.swing.JButton();
        ButtonEditLionParameters = new javax.swing.JButton();
        ButtonKillLion = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LabelSelectedAge = new javax.swing.JLabel();
        LabelSelectedHeight = new javax.swing.JLabel();
        LabelSelectedLeafArea = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelSelectedEnergy = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LabelGID = new javax.swing.JLabel();
        LabelSelectedGAge = new javax.swing.JLabel();
        LabelSelectedGEnergy = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LabelSelectedGHeight = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        LabelLID = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        LabelLAge = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        LabelLEnergy = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LabelSelectedLSize = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        LabelSelectedGStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        LabelNumberOfTrees = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LabelTAvgHeight = new javax.swing.JLabel();
        ButtonRun = new javax.swing.JButton();
        LabelYearsPassed = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextFieldYearToRun = new javax.swing.JTextField();
        ButtonStop = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        LabelAverageLeafArea = new javax.swing.JLabel();
        ButtonPaused = new javax.swing.JButton();
        ButtonGraphs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        LabelNumberOfGiraffes = new javax.swing.JLabel();
        LabelNumberOfLions = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        LabelGAvgHeight = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LabelGAvgNeckLength = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forest Simulation");
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Arena.setBackground(new java.awt.Color(152, 217, 234));
        Arena.setBorder(new javax.swing.border.MatteBorder(null));
        Arena.setPreferredSize(new java.awt.Dimension(1050, 550));
        Arena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArenaMouseClicked(evt);
            }
        });

        jPanel1.setOpaque(false);

        CheckBoxShowLight.setText("Show Light");
        CheckBoxShowLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxShowLightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CheckBoxShowLight)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(CheckBoxShowLight))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(152, 217, 234));
        jPanel2.setForeground(new java.awt.Color(152, 217, 234));

        ButtonGetTreeGenes.setText("Get Tree Genes");
        ButtonGetTreeGenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetTreeGenesActionPerformed(evt);
            }
        });

        ButtonGetGiraffeGenes.setText("Get Giraffe Genes");
        ButtonGetGiraffeGenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetGiraffeGenesActionPerformed(evt);
            }
        });

        ButtonKillPlant.setText("Kill Plant");
        ButtonKillPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKillPlantActionPerformed(evt);
            }
        });

        ButtonKillGiraffe.setText("Kill Giraffe");
        ButtonKillGiraffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKillGiraffeActionPerformed(evt);
            }
        });

        ButtonEditTreeParameters.setText("Edit Tree Parameters");
        ButtonEditTreeParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditTreeParametersActionPerformed(evt);
            }
        });

        ButtonEditGiraffeParameters.setText("Edit Giraffe Parameters");
        ButtonEditGiraffeParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditGiraffeParametersActionPerformed(evt);
            }
        });

        ButtonEditEnvironmentalParameters.setText("Edit Environmental Parameters");
        ButtonEditEnvironmentalParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditEnvironmentalParametersActionPerformed(evt);
            }
        });

        ButtonGetLionGenes.setText("Get Lion Genes");
        ButtonGetLionGenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetLionGenesActionPerformed(evt);
            }
        });

        ButtonEditLionParameters.setText("Edit Lion Parameters");
        ButtonEditLionParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditLionParametersActionPerformed(evt);
            }
        });

        ButtonKillLion.setText("Kill Lion");
        ButtonKillLion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKillLionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonGetTreeGenes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonGetGiraffeGenes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ButtonGetLionGenes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(ButtonKillPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonKillGiraffe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(ButtonKillLion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(ButtonEditTreeParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditGiraffeParameters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditLionParameters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditEnvironmentalParameters)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonEditLionParameters, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(ButtonEditEnvironmentalParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonEditTreeParameters, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(ButtonKillLion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(ButtonGetTreeGenes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonGetGiraffeGenes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonKillGiraffe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonKillPlant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonGetLionGenes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonEditGiraffeParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout ArenaLayout = new javax.swing.GroupLayout(Arena);
        Arena.setLayout(ArenaLayout);
        ArenaLayout.setHorizontalGroup(
            ArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArenaLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ArenaLayout.setVerticalGroup(
            ArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        getContentPane().add(Arena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setPreferredSize(new java.awt.Dimension(150, 550));
        Panel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 255));
        jLabel6.setText("For Selected Plant");
        Panel2.add(jLabel6);
        jLabel6.setBounds(12, 20, 126, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Age:");
        Panel2.add(jLabel3);
        jLabel3.setBounds(12, 82, 28, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Height:");
        Panel2.add(jLabel4);
        jLabel4.setBounds(12, 136, 44, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Leaf Area:");
        Panel2.add(jLabel11);
        jLabel11.setBounds(12, 163, 61, 17);

        LabelSelectedAge.setText(" ");
        LabelSelectedAge.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedAge);
        LabelSelectedAge.setBounds(80, 81, 50, 20);

        LabelSelectedHeight.setText(" ");
        LabelSelectedHeight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedHeight);
        LabelSelectedHeight.setBounds(80, 135, 50, 20);

        LabelSelectedLeafArea.setText(" ");
        LabelSelectedLeafArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedLeafArea);
        LabelSelectedLeafArea.setBounds(80, 162, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Energy:");
        Panel2.add(jLabel5);
        jLabel5.setBounds(12, 109, 49, 17);

        LabelSelectedEnergy.setText(" ");
        LabelSelectedEnergy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedEnergy);
        LabelSelectedEnergy.setBounds(80, 108, 50, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ID:");
        Panel2.add(jLabel12);
        jLabel12.setBounds(12, 54, 19, 17);

        LabelID.setText(" ");
        LabelID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelID);
        LabelID.setBounds(80, 53, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 102, 255));
        jLabel7.setText("For Selected Giraffe");
        Panel2.add(jLabel7);
        jLabel7.setBounds(12, 222, 138, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ID:");
        Panel2.add(jLabel13);
        jLabel13.setBounds(12, 256, 19, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Age:");
        Panel2.add(jLabel14);
        jLabel14.setBounds(12, 283, 28, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Energy:");
        Panel2.add(jLabel15);
        jLabel15.setBounds(12, 311, 49, 17);

        LabelGID.setText(" ");
        LabelGID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelGID);
        LabelGID.setBounds(80, 255, 50, 20);

        LabelSelectedGAge.setText(" ");
        LabelSelectedGAge.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedGAge);
        LabelSelectedGAge.setBounds(80, 283, 50, 20);

        LabelSelectedGEnergy.setText(" ");
        LabelSelectedGEnergy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedGEnergy);
        LabelSelectedGEnergy.setBounds(80, 310, 50, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Height:");
        Panel2.add(jLabel17);
        jLabel17.setBounds(12, 338, 44, 17);

        LabelSelectedGHeight.setText(" ");
        LabelSelectedGHeight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedGHeight);
        LabelSelectedGHeight.setBounds(80, 337, 50, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("For Selected Lion:");
        Panel2.add(jLabel1);
        jLabel1.setBounds(12, 417, 138, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("ID:");
        Panel2.add(jLabel20);
        jLabel20.setBounds(12, 451, 19, 17);

        LabelLID.setText(" ");
        LabelLID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelLID);
        LabelLID.setBounds(80, 450, 50, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Age:");
        Panel2.add(jLabel21);
        jLabel21.setBounds(12, 479, 28, 17);

        LabelLAge.setText(" ");
        LabelLAge.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelLAge);
        LabelLAge.setBounds(80, 478, 50, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Energy:");
        Panel2.add(jLabel22);
        jLabel22.setBounds(12, 506, 49, 17);

        LabelLEnergy.setText(" ");
        LabelLEnergy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelLEnergy);
        LabelLEnergy.setBounds(80, 505, 50, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Size:");
        Panel2.add(jLabel23);
        jLabel23.setBounds(12, 533, 28, 17);

        LabelSelectedLSize.setText(" ");
        LabelSelectedLSize.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedLSize);
        LabelSelectedLSize.setBounds(80, 532, 50, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Status:");
        Panel2.add(jLabel27);
        jLabel27.setBounds(12, 364, 44, 17);

        LabelSelectedGStatus.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        LabelSelectedGStatus.setText(" ");
        LabelSelectedGStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.add(LabelSelectedGStatus);
        LabelSelectedGStatus.setBounds(60, 370, 90, 16);

        getContentPane().add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 550));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 150));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Number Of Trees:");

        LabelNumberOfTrees.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNumberOfTrees.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Average height of the trees:");

        LabelTAvgHeight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonRun.setText("Run");
        ButtonRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonRunMousePressed(evt);
            }
        });
        ButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRunActionPerformed(evt);
            }
        });

        LabelYearsPassed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelYearsPassed.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Years Have Passed...");

        jLabel8.setText("Run the simulation for");

        jLabel10.setText("years");

        TextFieldYearToRun.setText("100000");

        ButtonStop.setText("Stop");
        ButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStopActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Average leaf area of the trees:");

        LabelAverageLeafArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonPaused.setText("Pause");
        ButtonPaused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPausedActionPerformed(evt);
            }
        });

        ButtonGraphs.setText("Show Graphs");
        ButtonGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGraphsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Number Of Giraffes:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Number Of Lions:");

        LabelNumberOfGiraffes.setText(" ");
        LabelNumberOfGiraffes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelNumberOfLions.setText(" ");
        LabelNumberOfLions.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Average height of the giraffes:");

        LabelGAvgHeight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Average Neck-Length of the giraffes:");

        LabelGAvgNeckLength.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelYearsPassed, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(ButtonGraphs, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldYearToRun, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(ButtonRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPaused)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelNumberOfLions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelNumberOfTrees, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelNumberOfGiraffes, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(26, 26, 26)
                                        .addComponent(LabelTAvgHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LabelGAvgHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                                .addGap(272, 272, 272)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelGAvgNeckLength, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(LabelAverageLeafArea, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))))
                        .addGap(339, 339, 339)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10)
                        .addComponent(TextFieldYearToRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonStop)
                        .addComponent(ButtonPaused))
                    .addComponent(LabelYearsPassed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonGraphs)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTAvgHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelAverageLeafArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelNumberOfTrees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(LabelNumberOfGiraffes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel26)
                        .addComponent(LabelGAvgNeckLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LabelGAvgHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(LabelNumberOfLions, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1210, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRunActionPerformed
       try{
        Constants.ArenaMoveByYears = Integer.parseInt(TextFieldYearToRun.getText());
        /*
         * Call the Forest.run() function when this button is clicked
         */
        SwingWorker s = new SwingWorker<Integer, Void>() {

            @Override
            public Integer doInBackground() {
                ButtonRun.setEnabled(false);
                Forest.run();

                return 0;
            }

            public void done() {
            }
        };
       
        
            s.execute();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(gui.g, "An Error Occured. Please try again.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_ButtonRunActionPerformed

    private void ButtonRunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRunMousePressed
        //Forest.run();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRunMousePressed

    private void ButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStopActionPerformed

        
        Forest.stop();
         gui.LabelTAvgHeight.setText("");
        gui.LabelNumberOfTrees.setText("");
        gui.LabelYearsPassed.setText("");
        gui.LabelAverageLeafArea.setText("");
        gui.ButtonPaused.setText("Pause");
        gui.LabelGAvgHeight.setText("");
        gui.LabelNumberOfGiraffes.setText("");
        gui.LabelNumberOfLions.setText("");
        gui.LabelGAvgNeckLength.setText("");
        gui.LabelSelectedAge.setText("");
        LabelID.setText("");
        LabelSelectedAge.setText(" ");
        LabelSelectedHeight.setText(" ");
        LabelSelectedLeafArea.setText(" ");
        LabelSelectedEnergy.setText("");
        LabelGID.setText("");
                LabelSelectedGAge.setText("");
                LabelSelectedGHeight.setText("");
                LabelSelectedGEnergy.setText("");
             
                    LabelSelectedGStatus.setText("");
         LabelLID.setText("");
                LabelLAge.setText("");
                LabelSelectedLSize.setText("");
                LabelLEnergy.setText("");
        
        ButtonRun.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonStopActionPerformed

    private void ButtonPausedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPausedActionPerformed
        Forest.pause();
    }//GEN-LAST:event_ButtonPausedActionPerformed

    private void ArenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArenaMouseClicked
        Point p = evt.getPoint();

        for (Tree t : Forest.arrayOfAliveTrees) {
            if (t != null && t.ContainsPoint(p.x, p.y)) {
                for (Tree t2 : Forest.arrayOfAliveTrees) {
                    if (t2 != null) {
                        t2.isSelected = false;
                    }
                }

                t.isSelected = true;
                LabelID.setText(t.id + "");
                LabelSelectedAge.setText(t.age + "");
                LabelSelectedHeight.setText(((Math.round(t.stemlength * 100)) / 100.0) + "");
                LabelSelectedLeafArea.setText(((Math.round(t.leafarea * 100)) / 100.0) + "");
                LabelSelectedEnergy.setText(Math.round(t.energy * 100) / 100.0 + "");
            }

        }

        for (giraffe t : Forest.arrayOfAliveGiraffes) {
            if (t != null && t.ContainsPoint(p.x, p.y)) {
                for (giraffe t2 : Forest.arrayOfAliveGiraffes) {
                    if (t2 != null) {
                        t2.isSelected = false;
                    }
                }

                t.isSelected = true;
                LabelGID.setText(t.id + "");
                LabelSelectedGAge.setText(t.age + "");
                LabelSelectedGHeight.setText(((Math.round(t.bodylength * 100)) / 100.0) + "");
                LabelSelectedGEnergy.setText(Math.round(t.energy * 100) / 100.0 + "");
                if(t.isHungry)
                    LabelSelectedGStatus.setText("Looking for food");
                if(t.LookingForFemale)
                    LabelSelectedGStatus.setText("Looking for females");
                if(t.isHungry==false&&t.LookingForFemale==false)
                    LabelSelectedGStatus.setText("Loitering");
            }

        }
        
        for (Lion t : Forest.arrayOfAliveLions) {
            if (t != null && t.ContainsPoint(p.x, p.y)) {
                for (Lion t2 : Forest.arrayOfAliveLions) {
                    if (t2 != null) {
                        t2.isSelected = false;
                    }
                }

                t.isSelected = true;
                LabelLID.setText(t.id + "");
                LabelLAge.setText(t.age + "");
                LabelSelectedLSize.setText(((Math.round(t.currentsize * 100)) / 100.0) + "");
                LabelLEnergy.setText(Math.round(t.energy * 100) / 100.0 + "");
            }

        }
        
        


        gui.Arena.repaint();
        gui.Arena.revalidate();


    }//GEN-LAST:event_ArenaMouseClicked

    private void ButtonGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGraphsActionPerformed
        Forest.graph.pack();
        RefineryUtilities.centerFrameOnScreen(Forest.graph);
        Forest.graph.setVisible(true);
        Forest.graph.repaint();
    }//GEN-LAST:event_ButtonGraphsActionPerformed

    private void ButtonGetTreeGenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetTreeGenesActionPerformed
        for (Tree t : Forest.arrayOfAliveTrees) {
            if (t != null && t.isSelected) {
                g2.LabelID.setText(t.id + "");
                g2.LabelMaxAge.setText(t.dna.maxage + "");
                g2.LabelMaxStemLength.setText(Math.round(t.dna.stemlength * 100) / 100.0 + "");
                g2.LabelMaxLeafArea.setText(Math.round(t.dna.leafarea * 100) / 100.0 + "");
                g2.LabelEnergyToSeed.setText(Math.round(t.dna.energytoseed * 100) / 100.0 + "");
                g2.TextFieldColor.setText("("+t.color.getRed()+","+t.color.getGreen()+","+t.color.getBlue()+")");
                g2.setVisible(true);
            }
        }
        if (g2.isVisible() == false) {
            JOptionPane.showMessageDialog(g, "No Tree selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_ButtonGetTreeGenesActionPerformed

    private void ButtonKillPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKillPlantActionPerformed

        for (Tree t : Forest.arrayOfAliveTrees) {
            if (t != null && t.isSelected) {
                t.kill();
            }
        }
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_ButtonKillPlantActionPerformed

    private void ButtonEditTreeParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditTreeParametersActionPerformed
        g3.setVisible(true);
    }//GEN-LAST:event_ButtonEditTreeParametersActionPerformed

    private void ButtonEditEnvironmentalParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditEnvironmentalParametersActionPerformed
        g6.setVisible(true);
    }//GEN-LAST:event_ButtonEditEnvironmentalParametersActionPerformed

    private void ButtonEditGiraffeParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditGiraffeParametersActionPerformed
        g5.setVisible(true);
    }//GEN-LAST:event_ButtonEditGiraffeParametersActionPerformed

    private void ButtonKillGiraffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKillGiraffeActionPerformed
        for (giraffe t : Forest.arrayOfAliveGiraffes) {
            if (t != null && t.isSelected) {
                t.kill();
            }
        }
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_ButtonKillGiraffeActionPerformed

    private void ButtonGetGiraffeGenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetGiraffeGenesActionPerformed
        for (giraffe t : Forest.arrayOfAliveGiraffes) {
            if (t != null && t.isSelected) {
                g4.LabelGID.setText(t.id + "");
                g4.LabelGMaxAge.setText(t.dna.maxage + "");
                g4.LabelGEnergyToReproduce.setText(Math.round(t.dna.energytoreproduce * 100) / 100.0 + "");
                g4.LabelGMaxSpeed.setText(Math.round(t.dna.maxspeed * 100) / 100.0 + "");
                g4.LabelGRatio.setText(Math.round(t.dna.neckbodyratio * 100) / 100.0 + "");
                g4.LabelGMaxHeight.setText(Math.round(t.dna.height * 100) / 100.0 + "");
                
                
                if (t.gender == false) {
                    g4.ComboGSex.setSelectedIndex(0);
                } else {
                    g4.ComboGSex.setSelectedIndex(1);
                }
                
                if(t.dna.camouflage.fromFemaleParent&&t.dna.camouflage.fromMaleParent)
                    g4.TextFieldCam.setSelectedIndex(2);
                if(t.dna.camouflage.fromFemaleParent==false&&t.dna.camouflage.fromMaleParent==false)
                    g4.TextFieldCam.setSelectedIndex(0);
                if(t.dna.camouflage.fromFemaleParent==true&&t.dna.camouflage.fromMaleParent==false)
                    g4.TextFieldCam.setSelectedIndex(1);
                if(t.dna.camouflage.fromFemaleParent==false&&t.dna.camouflage.fromMaleParent==true)
                    g4.TextFieldCam.setSelectedIndex(1);
                
                g4.setVisible(true);
            }
        }
        if (g4.isVisible() == false) {
            JOptionPane.showMessageDialog(g, "No Giraffe selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonGetGiraffeGenesActionPerformed

    private void CheckBoxShowLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxShowLightActionPerformed
        Constants.ArenaShowLight = CheckBoxShowLight.isSelected();
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_CheckBoxShowLightActionPerformed

    private void ButtonGetLionGenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetLionGenesActionPerformed
       for(Lion l:Forest.arrayOfAliveLions){
           if(l!=null&&l.isSelected){
               g8.TextBoxID.setText(l.id+"");
               g8.TextBoxMaxSpeed.setText(Math.round(100*l.currentmaxspeed)/100.0+"");
               g8.TextBoxPreyEfficiency.setText(Math.round(100*l.dna.preyefficiency)/100.0+"");
               g8.TextBoxMaxAge.setText(l.dna.maxage+"");
               g8.TextBoxMaxVision.setText(Math.round(100*l.dna.maxvision)/100.0+"");
               g8.TextBoxEnergyToReproduce.setText(Math.round(100*l.dna.energytoreproduce)/100.0+"");
               g8.TextBoxSize.setText(Math.round(100*l.dna.size)/100.0+"");
               
                
                if (l.gender == false) {
                    g8.ComboBoxGender.setSelectedIndex(0);
                } else {
                    g8.ComboBoxGender.setSelectedIndex(1);
                }
                
                g8.setVisible(true);
               
           }
       }
       
       if (g8.isVisible() == false) {
            JOptionPane.showMessageDialog(g, "No Lion selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonGetLionGenesActionPerformed

    private void ButtonEditLionParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditLionParametersActionPerformed
       g7.setVisible(true);
    }//GEN-LAST:event_ButtonEditLionParametersActionPerformed

    private void ButtonKillLionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKillLionActionPerformed
         for (Lion l : Forest.arrayOfAliveLions) {
            if (l != null && l.isSelected) {
                l.kill();
            }
        }
        gui.Arena.repaint();
        gui.Arena.revalidate();
    }//GEN-LAST:event_ButtonKillLionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * St the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                g = new gui();
                g.setVisible(true);

                g2 = new TreeGenesDisplay();
                g2.setLocation(500, 200);

                g3 = new EditTreeParameters();
                g3.setLocation(500, 200);

                g4 = new GiraffeGenesDisplay();
                g4.setLocation(500, 200);

                g5 = new EditGiraffeParameters();
                g5.setLocation(500, 200);

                g6 = new EditEnvironmentParameters();
                g6.setLocation(500, 200);
                
                g7=new EditLionParameters();
                g7.setLocation(500,200);
                
                g8=new LiongenesDisplay();
                g8.setLocation(500,200);
            }
        });

    }
    public static gui g;
    public static TreeGenesDisplay g2;
    public static EditTreeParameters g3;
    public static GiraffeGenesDisplay g4;
    public static EditGiraffeParameters g5;
    public static EditEnvironmentParameters g6;
    public static EditLionParameters g7;
    public static LiongenesDisplay g8;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Arena;
    private javax.swing.JButton ButtonEditEnvironmentalParameters;
    private javax.swing.JButton ButtonEditGiraffeParameters;
    private javax.swing.JButton ButtonEditLionParameters;
    private javax.swing.JButton ButtonEditTreeParameters;
    private javax.swing.JButton ButtonGetGiraffeGenes;
    private javax.swing.JButton ButtonGetLionGenes;
    private javax.swing.JButton ButtonGetTreeGenes;
    private javax.swing.JButton ButtonGraphs;
    private javax.swing.JButton ButtonKillGiraffe;
    private javax.swing.JButton ButtonKillLion;
    private javax.swing.JButton ButtonKillPlant;
    public static javax.swing.JButton ButtonPaused;
    public static javax.swing.JButton ButtonRun;
    public static javax.swing.JButton ButtonStop;
    private javax.swing.JCheckBox CheckBoxShowLight;
    public static javax.swing.JLabel LabelAverageLeafArea;
    public static javax.swing.JLabel LabelGAvgHeight;
    public static javax.swing.JLabel LabelGAvgNeckLength;
    public static javax.swing.JLabel LabelGID;
    public static javax.swing.JLabel LabelID;
    public static javax.swing.JLabel LabelLAge;
    public static javax.swing.JLabel LabelLEnergy;
    public static javax.swing.JLabel LabelLID;
    public static javax.swing.JLabel LabelNumberOfGiraffes;
    public static javax.swing.JLabel LabelNumberOfLions;
    public static javax.swing.JLabel LabelNumberOfTrees;
    public static javax.swing.JLabel LabelSelectedAge;
    public static javax.swing.JLabel LabelSelectedEnergy;
    public static javax.swing.JLabel LabelSelectedGAge;
    public static javax.swing.JLabel LabelSelectedGEnergy;
    public static javax.swing.JLabel LabelSelectedGHeight;
    public static javax.swing.JLabel LabelSelectedGStatus;
    public static javax.swing.JLabel LabelSelectedHeight;
    public static javax.swing.JLabel LabelSelectedLSize;
    public static javax.swing.JLabel LabelSelectedLeafArea;
    public static javax.swing.JLabel LabelTAvgHeight;
    public static javax.swing.JLabel LabelYearsPassed;
    private javax.swing.JPanel Panel2;
    public static javax.swing.JTextField TextFieldYearToRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
