/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forest;

import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class LiongenesDisplay extends javax.swing.JFrame {

    /**
     * Creates new form GenesDisplay
     */
    public LiongenesDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelID = new javax.swing.JLabel();
        LabelMaxSpeed = new javax.swing.JLabel();
        LabelEnergyToReproduce = new javax.swing.JLabel();
        LabelMaxVision = new javax.swing.JLabel();
        LabelMaxAge = new javax.swing.JLabel();
        TextBoxID = new javax.swing.JTextField();
        TextBoxMaxSpeed = new javax.swing.JTextField();
        TextBoxMaxAge = new javax.swing.JTextField();
        TextBoxEnergyToReproduce = new javax.swing.JTextField();
        TextBoxMaxVision = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        LabelPreyEfficiency = new javax.swing.JLabel();
        TextBoxPreyEfficiency = new javax.swing.JTextField();
        LabelSize = new javax.swing.JLabel();
        TextBoxSize = new javax.swing.JTextField();
        LabelGender = new javax.swing.JLabel();
        ComboBoxGender = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Genes of selected lion");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        LabelID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelID.setText("ID:");
        getContentPane().add(LabelID);
        LabelID.setBounds(20, 10, 50, 20);

        LabelMaxSpeed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxSpeed.setText("Maximum Speed");
        getContentPane().add(LabelMaxSpeed);
        LabelMaxSpeed.setBounds(20, 170, 139, 20);

        LabelEnergyToReproduce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelEnergyToReproduce.setText("Energy To Reproduce");
        getContentPane().add(LabelEnergyToReproduce);
        LabelEnergyToReproduce.setBounds(20, 90, 160, 20);

        LabelMaxVision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxVision.setText("Maximum Vision");
        getContentPane().add(LabelMaxVision);
        LabelMaxVision.setBounds(20, 130, 139, 20);

        LabelMaxAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMaxAge.setText("Maximum Age:");
        getContentPane().add(LabelMaxAge);
        LabelMaxAge.setBounds(20, 50, 130, 20);

        TextBoxID.setEditable(false);
        TextBoxID.setText("jTextField1");
        TextBoxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxIDActionPerformed(evt);
            }
        });
        getContentPane().add(TextBoxID);
        TextBoxID.setBounds(295, 10, 85, 25);

        TextBoxMaxSpeed.setText("jTextField1");
        getContentPane().add(TextBoxMaxSpeed);
        TextBoxMaxSpeed.setBounds(295, 170, 85, 25);

        TextBoxMaxAge.setText("jTextField2");
        getContentPane().add(TextBoxMaxAge);
        TextBoxMaxAge.setBounds(295, 50, 85, 25);

        TextBoxEnergyToReproduce.setText("jTextField3");
        getContentPane().add(TextBoxEnergyToReproduce);
        TextBoxEnergyToReproduce.setBounds(295, 90, 85, 25);

        TextBoxMaxVision.setText("jTextField1");
        getContentPane().add(TextBoxMaxVision);
        TextBoxMaxVision.setBounds(295, 130, 85, 25);

        ButtonSave.setBackground(new java.awt.Color(204, 204, 255));
        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSave);
        ButtonSave.setBounds(116, 330, 100, 25);

        LabelPreyEfficiency.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPreyEfficiency.setText("Prey Efficiency");
        getContentPane().add(LabelPreyEfficiency);
        LabelPreyEfficiency.setBounds(20, 210, 100, 20);

        TextBoxPreyEfficiency.setText("jTextField1");
        getContentPane().add(TextBoxPreyEfficiency);
        TextBoxPreyEfficiency.setBounds(295, 210, 85, 25);

        LabelSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelSize.setText("Maximum Size:");
        getContentPane().add(LabelSize);
        LabelSize.setBounds(20, 250, 110, 20);

        TextBoxSize.setText("jTextField1");
        getContentPane().add(TextBoxSize);
        TextBoxSize.setBounds(295, 250, 85, 25);

        LabelGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGender.setText("Gender");
        getContentPane().add(LabelGender);
        LabelGender.setBounds(20, 290, 50, 20);

        ComboBoxGender.setBackground(new java.awt.Color(204, 204, 255));
        ComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));
        ComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGenderActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxGender);
        ComboBoxGender.setBounds(295, 290, 85, 25);

        jLabel1.setBackground(new java.awt.Color(152, 217, 234));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest/resources/blue.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
try{
        
        for (Lion l : Forest.arrayOfAliveLions) {
            if (l != null && l.isSelected) {
                l.dna.maxage = Double.parseDouble(TextBoxMaxAge.getText());
                l.dna.energytoreproduce = Double.parseDouble(TextBoxEnergyToReproduce.getText());
                l.dna.maxvision = Double.parseDouble(TextBoxMaxVision.getText());
                l.dna.maxspeed = Double.parseDouble(TextBoxMaxSpeed.getText());
                l.dna.preyefficiency=Double.parseDouble(TextBoxPreyEfficiency.getText());
                l.dna.size=Double.parseDouble(TextBoxSize.getText());
                
                if (ComboBoxGender.getSelectedIndex() == 0) {
                    l.gender = false;
                } else {
                    l.gender = true;
                }
            }
        }

        gui.g8.setVisible(false);
        
}

catch(Exception e){
    JOptionPane.showMessageDialog(gui.g8, "An Error Occured.Please Try Again.", "Warning", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void TextBoxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBoxIDActionPerformed

    private void ComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiongenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiongenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiongenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiongenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LiongenesDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ButtonSave;
    public static javax.swing.JComboBox ComboBoxGender;
    public static javax.swing.JLabel LabelEnergyToReproduce;
    public static javax.swing.JLabel LabelGender;
    public static javax.swing.JLabel LabelID;
    public static javax.swing.JLabel LabelMaxAge;
    public static javax.swing.JLabel LabelMaxSpeed;
    public static javax.swing.JLabel LabelMaxVision;
    public static javax.swing.JLabel LabelPreyEfficiency;
    public static javax.swing.JLabel LabelSize;
    public static javax.swing.JTextField TextBoxEnergyToReproduce;
    public static javax.swing.JTextField TextBoxID;
    public static javax.swing.JTextField TextBoxMaxAge;
    public static javax.swing.JTextField TextBoxMaxSpeed;
    public static javax.swing.JTextField TextBoxMaxVision;
    public static javax.swing.JTextField TextBoxPreyEfficiency;
    public static javax.swing.JTextField TextBoxSize;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
