/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forest;

import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class TreeGenesDisplay extends javax.swing.JFrame {

    /**
     * Creates new form GenesDisplay
     */
    public TreeGenesDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelID = new javax.swing.JTextField();
        LabelMaxStemLength = new javax.swing.JTextField();
        LabelMaxAge = new javax.swing.JTextField();
        LabelMaxLeafArea = new javax.swing.JTextField();
        LabelEnergyToSeed = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TextFieldColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Genes of Selected Plant");
        setMinimumSize(new java.awt.Dimension(335, 290));
        setPreferredSize(new java.awt.Dimension(310, 270));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Maximum Stem Length:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Maximum Leaf Area:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Energy To Seed:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Maximum Age:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 60, 120, 30);

        LabelID.setEditable(false);
        LabelID.setText("jTextField1");
        getContentPane().add(LabelID);
        LabelID.setBounds(220, 30, 85, 30);

        LabelMaxStemLength.setText("jTextField1");
        getContentPane().add(LabelMaxStemLength);
        LabelMaxStemLength.setBounds(220, 90, 85, 30);

        LabelMaxAge.setText("jTextField2");
        getContentPane().add(LabelMaxAge);
        LabelMaxAge.setBounds(220, 60, 85, 30);

        LabelMaxLeafArea.setText("jTextField3");
        getContentPane().add(LabelMaxLeafArea);
        LabelMaxLeafArea.setBounds(220, 120, 85, 30);

        LabelEnergyToSeed.setText("jTextField1");
        getContentPane().add(LabelEnergyToSeed);
        LabelEnergyToSeed.setBounds(220, 150, 85, 30);

        ButtonSave.setBackground(new java.awt.Color(204, 204, 255));
        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSave);
        ButtonSave.setBounds(140, 220, 61, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Color (RGB):");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 110, 30);

        TextFieldColor.setEditable(false);
        TextFieldColor.setText("jTextField1");
        getContentPane().add(TextFieldColor);
        TextFieldColor.setBounds(220, 180, 85, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forest/resources/blue.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 360, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
try{
        
        for (Tree t : Forest.arrayOfAliveTrees) {
            if (t != null && t.isSelected) {
                t.dna.maxage = Integer.parseInt(LabelMaxAge.getText());
                t.dna.stemlength = Double.parseDouble(LabelMaxStemLength.getText());
                t.dna.energytoseed = Double.parseDouble(LabelEnergyToSeed.getText());
                t.dna.leafarea = Double.parseDouble(LabelMaxLeafArea.getText());
            }
        }

        GUI.g2.setVisible(false);
        
}

catch(Exception e){
    JOptionPane.showMessageDialog(GUI.g2, "An Error Occured.Please Try Again.", "Warning", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_ButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreeGenesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TreeGenesDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSave;
    public static javax.swing.JTextField LabelEnergyToSeed;
    public static javax.swing.JTextField LabelID;
    public static javax.swing.JTextField LabelMaxAge;
    public static javax.swing.JTextField LabelMaxLeafArea;
    public static javax.swing.JTextField LabelMaxStemLength;
    public javax.swing.JTextField TextFieldColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
